meta_product_name: "Hermes Land"
meta_title: "Hermes - Find a buddy, learn a language!"
meta_description: "Hermes Land connects people with shared interests to learn a new language together"
meta_image: "cover.jpg" # in `app/assets/images/`
